# Generated by Django 5.2.3 on 2025-07-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('img_src_filepath', models.CharField(blank=True, max_length=250)),
                ('img_crp_filepath', models.CharField(blank=True, max_length=250)),
                ('loaded_src', models.ImageField(blank=True, upload_to='')),
                ('loaded_crp', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CardSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('subset', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('attributes', models.TextField(blank=True)),
                ('unknown_words', models.TextField(blank=True)),
                ('title_similarity', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('parent_card', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='core.card')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=100)),
                ('listing_date', models.DateTimeField()),
                ('img_url', models.CharField(max_length=250)),
                ('thumb_url', models.CharField(max_length=250)),
                ('search_result', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.cardsearchresult')),
            ],
        ),
        migrations.CreateModel(
            name='ListingTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('parent_listing', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='core.productlisting')),
            ],
        ),
    ]
