# Generated by Django 5.2.3 on 2025-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='title_similarity',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='collapsed_tokens',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
