# Generated by Django 5.2.3 on 2025-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cardsearchresult_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
