# Generated by Django 5.2.3 on 2025-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cardsearchresult_response_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='latest_crop_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_crop_rotate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_crop_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_crop_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_rotate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_y',
            field=models.IntegerField(default=0),
        ),
    ]
