# Generated by Django 5.2.3 on 2025-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_card_latest_crop_height_card_latest_crop_rotate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='loaded_portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='portrait_filepath',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
