# Generated by Django 5.2.3 on 2025-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_loaded_portrait_card_portrait_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='crop_canvas_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='crop_canvas_top',
            field=models.IntegerField(default=0),
        ),
    ]
