# Generated by Django 5.2.3 on 2025-07-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_crop_canvas_left_card_crop_canvas_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='crop_canvas_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='crop_canvas_top',
            field=models.FloatField(default=0.0),
        ),
    ]
