# Generated by Django 5.2.3 on 2025-07-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_card_crop_canvas_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
