# Generated by Django 5.2.3 on 2025-07-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cardsearchresult_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='first_name_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='last_name_m',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
