# Generated by Django 5.2.3 on 2025-07-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_name_cardsearchresult_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='first_name_m',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='last_name_m',
        ),
    ]
