# Generated by Django 5.2.3 on 2025-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cardsearchresult_first_name_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='brand_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='brand_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_number_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_number_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='city_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='city_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='first_name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='first_name_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_name_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='last_name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='last_name_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='serial_number_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='serial_number_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='subset_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='subset_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='team_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='team_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='year_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='year_m',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
