# Generated by Django 5.2.3 on 2025-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cardsearchresult_brand_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='name_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='search_string',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='title_to_be',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
