# Generated by Django 5.2.3 on 2025-07-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cardsearchresult_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='title_to_be_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='title_to_be_m',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
