# Generated by Django 5.2.3 on 2025-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cardsearchresult_title_to_be_is_manual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='crop_canvas_left',
            new_name='crop_front_canvas_left',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='crop_canvas_top',
            new_name='crop_front_canvas_top',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='img_crp_filepath',
            new_name='front_crp_filepath',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='img_src_filepath',
            new_name='front_src_filepath',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='latest_crop_height',
            new_name='latest_front_crop_height',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='latest_crop_rotate',
            new_name='latest_front_crop_rotate',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='latest_crop_width',
            new_name='latest_front_crop_width',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='latest_crop_x',
            new_name='latest_front_crop_x',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='latest_crop_y',
            new_name='latest_front_crop_y',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='loaded_crp',
            new_name='loaded_front_crp',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='loaded_src',
            new_name='loaded_front_src',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='search_date',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='card',
            name='back_crp_filepath',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='back_src_filepath',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='card',
            name='crop_back_canvas_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='crop_back_canvas_top',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_back_crop_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_back_crop_rotate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_back_crop_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_back_crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='latest_back_crop_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='loaded_back_crp',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='loaded_back_src',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
