# Generated by Django 5.2.3 on 2025-07-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_crop_canvas_left_card_crop_front_canvas_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='crop_height',
            new_name='crop_front_height',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='crop_rotate',
            new_name='crop_front_rotate',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='crop_width',
            new_name='crop_front_width',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='crop_x',
            new_name='crop_front_x',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='crop_y',
            new_name='crop_front_y',
        ),
    ]
