# Generated by Django 5.2.3 on 2025-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_crop_height_cardsearchresult_crop_front_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('rotate', models.FloatField(default=0.0)),
                ('display_offset_left', models.FloatField(default=0.0)),
                ('display_offset_top', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='back_crp_filepath',
        ),
        migrations.RemoveField(
            model_name='card',
            name='back_src_filepath',
        ),
        migrations.RemoveField(
            model_name='card',
            name='crop_back_canvas_left',
        ),
        migrations.RemoveField(
            model_name='card',
            name='crop_back_canvas_top',
        ),
        migrations.RemoveField(
            model_name='card',
            name='crop_front_canvas_left',
        ),
        migrations.RemoveField(
            model_name='card',
            name='crop_front_canvas_top',
        ),
        migrations.RemoveField(
            model_name='card',
            name='front_crp_filepath',
        ),
        migrations.RemoveField(
            model_name='card',
            name='front_src_filepath',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_back_crop_height',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_back_crop_rotate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_back_crop_width',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_back_crop_x',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_back_crop_y',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_front_crop_height',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_front_crop_rotate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_front_crop_width',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_front_crop_x',
        ),
        migrations.RemoveField(
            model_name='card',
            name='latest_front_crop_y',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loaded_back_crp',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loaded_back_src',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loaded_front_crp',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loaded_front_src',
        ),
        migrations.RemoveField(
            model_name='card',
            name='loaded_portrait',
        ),
        migrations.RemoveField(
            model_name='card',
            name='portrait_filepath',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_front_height',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_front_rotate',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_front_width',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_front_x',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_front_y',
        ),
    ]
