# Generated by Django 5.2.3 on 2025-07-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cropparams_croppedimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cropped_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_portrait', to='core.croppedimage'),
        ),
        migrations.AddField(
            model_name='card',
            name='cropped_reverse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_reverse_crop', to='core.croppedimage'),
        ),
        migrations.AddField(
            model_name='card',
            name='portrait_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_cropped', to='core.croppedimage'),
        ),
        migrations.AddField(
            model_name='card',
            name='reverse_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_reverse', to='core.croppedimage'),
        ),
        migrations.AddField(
            model_name='card',
            name='uploaded_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_upload', to='core.croppedimage'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='crop_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr', to='core.cropparams'),
        ),
        migrations.AddField(
            model_name='croppedimage',
            name='crop_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.cropparams'),
        ),
    ]
