# Generated by Django 5.2.3 on 2025-07-29 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_card_cropped_image_card_cropped_reverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='portrait_reverse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_as_reverse_portrait', to='core.croppedimage'),
        ),
    ]
