# Generated by Django 5.2.3 on 2025-07-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_card_portrait_reverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reverse_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
