# Generated by Django 5.2.3 on 2025-07-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_card_reverse_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='crop_params',
        ),
        migrations.RemoveField(
            model_name='croppedimage',
            name='crop_params',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='front_crop_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr_as_front', to='core.cropparams'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='reverse_crop_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr_as_reverse', to='core.cropparams'),
        ),
        migrations.AddField(
            model_name='cropparams',
            name='crop_params',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_params', to='core.croppedimage'),
        ),
    ]
