# Generated by Django 5.2.3 on 2025-07-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_cardsearchresult_crop_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropparams',
            name='crop_params',
        ),
        migrations.AddField(
            model_name='cropparams',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crop_params', to='core.croppedimage'),
        ),
    ]
