# Generated by Django 5.2.3 on 2025-08-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.collection'),
            preserve_default=False,
        ),
    ]
