# Generated by Django 5.2.3 on 2025-08-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_card_collection'),
    ]

    operations = [
    ]
