# Generated by Django 5.2.3 on 2025-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20250808_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
