# Generated by Django 5.2.3 on 2025-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cardsearchresult_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_m',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='search_string',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
