# Generated by Django 5.2.3 on 2025-08-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cardsearchresult_parallel_and_more'),
        ('services', '0016_brand_primary_token_cardattribute_primary_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtitle',
            name='brand_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.brand'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='card_attribute_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.cardattribute'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='city_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.city'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='condition_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.condition'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='known_name_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.knownname'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='subset_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.subset'),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='team_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.team'),
        ),
    ]
