# Generated by Django 5.2.3 on 2025-08-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_listingtitle_brand_tokens_and_more'),
        ('services', '0017_alter_season_parent_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingtitle',
            name='parallel_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.parallel'),
        ),
    ]
