# Generated by Django 5.2.3 on 2025-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_listingtitle_parallel_tokens'),
        ('services', '0019_cardname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='first_name_is_manual',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='first_name_m',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='last_name_is_manual',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='last_name_m',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_name_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_name_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listingtitle',
            name='card_name_tokens',
            field=models.ManyToManyField(blank=True, related_name='listing_titles', to='services.cardname'),
        ),
    ]
