# Generated by Django 5.2.3 on 2025-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_cardsearchresult_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='subcollections',
            field=models.ManyToManyField(blank=True, related_name='parent_collections', to='core.collection'),
        ),
    ]
