# Generated by Django 5.2.3 on 2025-08-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_collection_subcollections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='subcollections',
        ),
        migrations.AddField(
            model_name='collection',
            name='parent_collection',
            field=models.ForeignKey('self', on_delete=models.CASCADE, related_name="subcollections", null=True),
            preserve_default=False,
        ),
    ]
