# Generated by Django 5.2.3 on 2025-08-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_collection_subcollections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='parent_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='core.collection'),
        ),
    ]
