# Generated by Django 5.2.3 on 2025-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_collection_parent_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_set',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='league',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='sport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
