# Generated by Django 5.2.3 on 2025-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cardsearchresult_full_set_cardsearchresult_full_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='features',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
