# Generated by Django 5.2.3 on 2025-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cardsearchresult_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_listing_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='list_price',
            field=models.FloatField(default=0.0),
        ),
    ]
