# Generated by Django 5.2.3 on 2025-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cardsearchresult_ebay_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_item_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_offer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
