# Generated by Django 5.2.3 on 2025-08-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_cardsearchresult_ebay_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='parallel_manual',
            new_name='parallel_is_manual',
        ),
    ]
