# Generated by Django 5.2.3 on 2025-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_parallel_manual_cardsearchresult_parallel_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='ebay_price',
            field=models.FloatField(default=0.0),
        ),
    ]
