# Generated by Django 5.2.3 on 2025-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_productlisting_ebay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_high_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_low_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_mean_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_median_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_mode_price',
            field=models.FloatField(default=0.0),
        ),
    ]
