# Generated by Django 5.2.3 on 2025-09-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_cardsearchresult_ebay_high_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='atttribute_flags',
            field=models.JSONField(default=list),
        ),
    ]
