# Generated by Django 5.2.3 on 2025-09-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cardsearchresult_atttribute_flags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='atttribute_flags',
            new_name='attribute_flags',
        ),
    ]
