# Generated by Django 5.2.3 on 2025-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_atttribute_flags_cardsearchresult_attribute_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('revwiewed', 'Reviewed'), ('saved', 'Saved')], default='new', max_length=20),
        ),
    ]
