# Generated by Django 5.2.3 on 2025-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_cardsearchresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='ebay_offer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cropped', 'Cropped'), ('searched', 'Searched'), ('saved', 'Saved'), ('listed', 'Listed')], default='new', max_length=20),
        ),
    ]
