# Generated by Django 5.2.3 on 2025-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_cardsearchresult_ebay_offer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_listing_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
