# Generated by Django 5.2.3 on 2025-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_cardsearchresult_ebay_listing_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cropped', 'Cropped'), ('searched', 'Searched'), ('saved', 'Saved'), ('listed', 'Listed'), ('hold', 'Hold')], default='new', max_length=20),
        ),
    ]
