# Generated by Django 5.2.3 on 2025-09-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_card_notes_alter_cardsearchresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_filtered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtered_listings', to='core.cardsearchresult'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='attribute_flags',
            field=models.JSONField(default=dict),
        ),
    ]
