# Generated by Django 5.2.3 on 2025-09-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_productlisting_csr_as_filtered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='csr_as_filtered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtered_listings', to='core.cardsearchresult'),
        ),
    ]
