# Generated by Django 5.2.3 on 2025-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_productlisting_csr_as_filtered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_filtered',
        ),
    ]
