# Generated by Django 5.2.3 on 2025-09-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_productlisting_csr_as_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_filtered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filtered_listings', to='core.cardsearchresult'),
        ),
    ]
