# Generated by Django 5.2.3 on 2025-09-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_productlisting_csr_as_filtered'),
        ('services', '0029_settings_nr_std_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_parallel', to='services.parallel'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_parallel', to='services.parallel'),
        ),
    ]
