# Generated by Django 5.2.3 on 2025-09-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_cardsearchresult_parallel_available_tokens_and_more'),
        ('services', '0029_settings_nr_std_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='brand_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_brand', to='services.brand'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='brand_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_brand', to='services.brand'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_name_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_card_name', to='services.cardname'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_name_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_card_name', to='services.cardname'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_number_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_card_number', to='services.cardnumber'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='card_number_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_card_number', to='services.cardnumber'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='city_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_city', to='services.city'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='city_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_city', to='services.city'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_name_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_full_name', to='services.knownname'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='full_name_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_full_name', to='services.knownname'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='serial_number_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_serial_number', to='services.serialnumber'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='serial_number_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_serial_number', to='services.serialnumber'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='subset_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_subset', to='services.subset'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='subset_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_subset', to='services.subset'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='team_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_team', to='services.team'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='team_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_team', to='services.team'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='year_available_tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='csr_as_available_year', to='services.season'),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='year_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='csr_as_selected_year', to='services.season'),
        ),
    ]
