# Generated by Django 5.2.3 on 2025-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_cardsearchresult_brand_available_tokens_and_more'),
        ('services', '0029_settings_nr_std_devs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_brand', to='services.brand'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_name_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_card_name', to='services.cardname'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_number_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_card_number', to='services.cardnumber'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='city_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_city', to='services.city'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='full_name_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_full_name', to='services.knownname'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='parallel_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_parallel', to='services.parallel'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='serial_number_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_serial_number', to='services.serialnumber'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_subset', to='services.subset'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='team_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_team', to='services.team'),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='year_available_tokens',
            field=models.ManyToManyField(blank=True, related_name='csr_as_available_year', to='services.season'),
        ),
    ]
