# Generated by Django 5.2.3 on 2025-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_cardsearchresult_brand_available_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='listing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
