# Generated by Django 5.2.3 on 2025-09-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_productlisting_format_productlisting_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_listings', to='core.cardsearchresult'),
        ),
    ]
