# Generated by Django 5.2.3 on 2025-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_productlisting_csr_as_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='search_string_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='search_string_m',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
