# Generated by Django 5.2.3 on 2025-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_cardsearchresult_search_string_is_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='search_string_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
