# Generated by Django 5.2.3 on 2025-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_cardsearchresult_search_string_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='search_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
