# Generated by Django 5.2.3 on 2025-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_cardsearchresult_search_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='display_date',
            field=models.DateTimeField(null=True),
        ),
    ]
