# Generated by Django 5.2.3 on 2025-10-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_productlisting_display_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='display_date',
        ),
    ]
