# Generated by Django 5.2.3 on 2025-10-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_productlisting_display_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_avg_sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_high_sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_last_five_avg_sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_last_sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_low_sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_open_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='open_listings', to='core.cardsearchresult'),
        ),
    ]
