# Generated by Django 5.2.3 on 2025-10-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_cardsearchresult_ebay_avg_sold_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='full_set',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='full_team',
        ),
    ]
