# Generated by Django 5.2.3 on 2025-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_cardsearchresult_full_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='img_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
