# Generated by Django 5.2.3 on 2025-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_productlisting_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='listing_details',
            field=models.TextField(blank=True),
        ),
    ]
