# Generated by Django 5.2.3 on 2025-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_card_listing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtitle',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
