# Generated by Django 5.2.3 on 2025-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_listingtitle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='required_or_excluded',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
