# Generated by Django 5.2.3 on 2025-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_cardsearchresult_required_or_excluded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='required_or_excluded',
            new_name='filter_terms',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='search_string',
            new_name='sold_search_string',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='search_string_is_manual',
            new_name='sold_search_string_is_manual',
        ),
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='search_string_m',
            new_name='sold_search_string_m',
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='filter_terms_is_manual',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='filter_terms_m',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='text_search_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='text_search_string_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='text_search_string_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
