# Generated by Django 5.2.3 on 2025-10-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_rename_required_or_excluded_cardsearchresult_filter_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_refined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refined_listings', to='core.cardsearchresult'),
        ),
    ]
