# Generated by Django 5.2.3 on 2025-10-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_productlisting_csr_as_refined'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
