# Generated by Django 5.2.3 on 2025-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_collection_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='filter_terms_is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
