# Generated by Django 5.2.3 on 2025-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_cardsearchresult_filter_terms_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_name_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='parallel_m',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='serial_number_m',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
