# Generated by Django 5.2.3 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_cardsearchresult_card_name_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
