# Generated by Django 5.2.3 on 2025-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_cardsearchresult_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='parallel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
