# Generated by Django 5.2.3 on 2025-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_cardsearchresult_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='filter_terms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='filter_terms_m',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
