# Generated by Django 5.2.3 on 2025-10-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_cardsearchresult_filter_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_sold_refined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_refined_listings', to='core.cardsearchresult'),
        ),
    ]
