# Generated by Django 5.2.3 on 2025-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_cardsearchresult_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='back_cropping_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='front_cropping_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='id_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='pricing_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='refinement_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
    ]
