# Generated by Django 5.2.3 on 2025-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_cardsearchresult_back_cropping_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed')], default='unexecuted', max_length=20),
        ),
    ]
