# Generated by Django 5.2.3 on 2025-10-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_cardsearchresult_overall_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_open_listing',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_id_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_listings', to='core.cardsearchresult'),
        ),
    ]
