# Generated by Django 5.2.3 on 2025-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_productlisting_csr_as_open_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_number_m',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
