# Generated by Django 5.2.3 on 2025-10-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_productlisting_csr_as_sold_refined_wide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_refined_wide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refined_wide_listings', to='core.cardsearchresult'),
        ),
    ]
