# Generated by Django 5.2.3 on 2025-10-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_productlisting_csr_as_refined_wide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_refined',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_refined_wide',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='text_listings', to='core.cardsearchresult'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_text_refined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='text_refined_listings', to='core.cardsearchresult'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_text_refined_wide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='text_refined_wide_listings', to='core.cardsearchresult'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='csr_as_text_wide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='text_wide_listings', to='core.cardsearchresult'),
        ),
    ]
