# Generated by Django 5.2.3 on 2025-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_productlisting_csr_as_refined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='full_name_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='year_m',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
