# Generated by Django 5.2.3 on 2025-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_cardsearchresult_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='team_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
