# Generated by Django 5.2.3 on 2025-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_cardsearchresult_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='city_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
