# Generated by Django 5.2.3 on 2025-10-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_cardsearchresult_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_filtered',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_id_listing',
        ),
        migrations.CreateModel(
            name='ListingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_refined', models.BooleanField(default=False)),
                ('is_wide', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_groups', to='core.cardsearchresult')),
            ],
        ),
        migrations.AddField(
            model_name='productlisting',
            name='listing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='core.listinggroup'),
        ),
    ]
