# Generated by Django 5.2.3 on 2025-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_productlisting_csr_as_filtered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='is_img',
            field=models.BooleanField(default=False),
        ),
    ]
