# Generated by Django 5.2.3 on 2025-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_listinggroup_is_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_sold',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_sold_refined',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_sold_refined_wide',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_sold_wide',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_text',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_text_refined',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_text_refined_wide',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='csr_as_text_wide',
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='search_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
