# Generated by Django 5.2.3 on 2025-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_productlisting_csr_as_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='border_width',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='color',
            field=models.CharField(default='rgba(204, 153, 0, 0.8)', max_length=50),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='line_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('dotted', 'Dotted')], default='solid', max_length=10),
        ),
    ]
