# Generated by Django 5.2.3 on 2025-10-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_listinggroup_border_width_listinggroup_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='max_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='max_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='min_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='min_price',
            field=models.FloatField(default=0.0),
        ),
    ]
