# Generated by Django 5.2.3 on 2025-10-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_listinggroup_display_listinggroup_max_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listinggroup',
            unique_together={('search_result', 'is_sold', 'is_refined', 'is_wide', 'is_img')},
        ),
    ]
