# Generated by Django 5.2.3 on 2025-10-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_listinggroup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='listing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.listinggroup'),
        ),
    ]
