# Generated by Django 5.2.3 on 2025-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_productlisting_listing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_msrp',
            field=models.FloatField(default=0.0),
        ),
    ]
