# Generated by Django 5.2.3 on 2025-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_cardsearchresult_ebay_msrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='filter_terms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='id_string',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listinggroup',
            name='search_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
