# Generated by Django 5.2.3 on 2025-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_listinggroup_filter_terms_listinggroup_id_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='ebay_msrp',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
