# Generated by Django 5.2.3 on 2025-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_cardsearchresult_ebay_msrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='shareable_link_front',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='shareable_link_reverse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
