# Generated by Django 5.2.3 on 2025-10-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_productgroup_cardsearchresult_ebay_product_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='ebay_item_id',
            new_name='sku',
        ),
    ]
