# Generated by Django 5.2.3 on 2025-10-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_rename_ebay_item_id_cardsearchresult_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='variation_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='ebay_product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.productgroup'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
