# Generated by Django 5.2.3 on 2025-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_cardsearchresult_variation_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='name',
            new_name='group_key',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='group_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
