# Generated by Django 5.2.3 on 2025-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_rename_name_productgroup_group_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='variation_title',
            new_name='variation_title_base',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='variation_data',
            field=models.JSONField(default=dict),
        ),
    ]
