# Generated by Django 5.2.3 on 2025-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_rename_variation_title_cardsearchresult_variation_title_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='group_image_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
