# Generated by Django 5.2.3 on 2025-11-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_productgroup_group_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='ebay_listed_under_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_lead_sku', to='core.cardsearchresult'),
        ),
    ]
