# Generated by Django 5.2.3 on 2025-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_cardsearchresult_ebay_listed_under_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
