# Generated by Django 5.2.3 on 2025-11-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_cardsearchresult_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsearchresult',
            old_name='grade',
            new_name='number_grade',
        ),
    ]
