# Generated by Django 5.2.3 on 2025-11-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_rename_grade_cardsearchresult_number_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=250)),
                ('max_len', models.IntegerField(default=0)),
                ('min_len', models.IntegerField(default=0)),
            ],
        ),
    ]
