# Generated by Django 5.2.3 on 2025-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_fieldstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('ready to price', 'Ready to price'), ('ready to list', 'Ready to list'), ('listed', 'Listed')], default='imported', max_length=20),
        ),
    ]
