# Generated by Django 5.2.3 on 2026-02-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_cardsearchresult_back_cropping_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='back_cropping_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='front_cropping_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='id_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='pricing_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='refinement_status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='unexecuted', max_length=20),
        ),
    ]
