# Generated by Django 5.2.3 on 2026-02-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_cardsearchresult_back_cropping_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_datetime', models.DateTimeField(null=True)),
                ('list_price', models.FloatField(default=0.0)),
                ('list_qty', models.IntegerField(default=0)),
                ('listing_id', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('offer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('msrp', models.FloatField(default=0.0, null=True)),
                ('variation_title_base', models.CharField(blank=True, max_length=50, null=True)),
                ('shareable_link_front', models.CharField(blank=True, max_length=250, null=True)),
                ('shareable_link_reverse', models.CharField(blank=True, max_length=250, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listed_card', to='core.card')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listed_products_info', to='core.productgroup')),
                ('sub_cards', models.ManyToManyField(blank=True, null=True, related_name='listed_subcard', to='core.card')),
            ],
        ),
    ]
