# Generated by Django 5.2.3 on 2026-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_listedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='listing_detail_text',
            field=models.TextField(blank=True),
        ),
    ]
