# Generated by Django 5.2.3 on 2026-02-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_listedinfo_listing_detail_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='listing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listed_card_info', to='core.card'),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='sub_cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='listed_subcard_info', to='core.card'),
        ),
    ]
