# Generated by Django 5.2.3 on 2026-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_listedinfo_listing_notes_alter_listedinfo_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='listing_details',
        ),
    ]
