# Generated by Django 5.2.3 on 2026-02-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_card_listing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedinfo',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_card_info', to='core.card'),
        ),
    ]
