# Generated by Django 5.2.3 on 2026-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_listedinfo_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='card_name_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='city_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='condition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='features',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='full_name_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='league',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='name_m',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='sold_search_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='sold_search_string_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='sport',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='team',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='team_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='text_search_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='text_search_string_m',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='title_to_be',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='title_to_be_m',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listinggroup',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listingtitle',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='format',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='item_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
