# Generated by Django 5.2.3 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_cardsearchresult_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='back_cropping_status',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='front_cropping_status',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='id_status',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='pricing_status',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='refinement_status',
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('priced', 'Priced'), ('listed', 'Listed'), ('running', 'Running'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
    ]
