# Generated by Django 5.2.3 on 2026-03-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_cardsearchresult_overall_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listinggroup',
            unique_together={('search_result', 'label')},
        ),
    ]
