# Generated by Django 5.2.3 on 2026-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_listinggroup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='avg_price',
            field=models.FloatField(default=0.0),
        ),
    ]
