# Generated by Django 5.2.3 on 2026-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_listinggroup_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='recent_avg_price',
            field=models.FloatField(default=0.0),
        ),
    ]
