# Generated by Django 5.2.3 on 2026-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_listinggroup_recent_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='price_spread',
            field=models.FloatField(default=0.0),
        ),
    ]
