# Generated by Django 5.2.3 on 2026-03-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_listinggroup_price_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.FloatField(default=True),
        ),
    ]
