# Generated by Django 5.2.3 on 2026-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_card_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
