# Generated by Django 5.2.3 on 2026-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_collection_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
