# Generated by Django 5.2.3 on 2026-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_listinggroup_modification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='listing_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='offer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='sku',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='variation_title_base',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listinggroup',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
