# Generated by Django 5.2.3 on 2026-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_alter_card_value_alter_listedinfo_listing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_avg_sold_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_high_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_high_sold_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_last_five_avg_sold_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_last_sold_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_low_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_low_sold_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_mean_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_median_price',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_mode_price',
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('listed', 'Listed'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
    ]
