# Generated by Django 5.2.3 on 2026-04-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_remove_cardsearchresult_ebay_avg_sold_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImageArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('data', models.JSONField()),
                ('path', models.CharField(default='', max_length=500)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['original_id'], name='core_croppe_origina_b23322_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('data', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('cropped_img_archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_as_primary', to='core.croppedimagearchive')),
                ('cropped_rev_archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_as_reverse', to='core.croppedimagearchive')),
            ],
            options={
                'indexes': [models.Index(fields=['original_id'], name='core_cardar_origina_d3695c_idx')],
            },
        ),
    ]
