# Generated by Django 5.2.3 on 2026-04-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_croppedimagearchive_cardarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='cardarchive',
            name='asr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_card', to='core.csrarchive'),
        ),
    ]
