# Generated by Django 5.2.3 on 2026-04-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_csrarchive_cardarchive_asr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropparams',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_params', to='core.croppedimage'),
        ),
    ]
