# Generated by Django 5.2.3 on 2026-04-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_cropparams_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppedimagearchive',
            name='data',
        ),
    ]
