# Generated by Django 5.2.3 on 2026-04-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_remove_croppedimagearchive_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='ebay_listed_under_sku',
        ),
    ]
