# Generated by Django 5.2.3 on 2026-04-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_remove_cardsearchresult_ebay_listed_under_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedInfoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
        migrations.AddField(
            model_name='cardarchive',
            name='li',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_card', to='core.listedinfoarchive'),
        ),
    ]
