# Generated by Django 5.2.3 on 2026-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_listedinfoarchive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfoarchive',
            name='original_pg',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
