# Generated by Django 5.2.3 on 2026-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_listedinfoarchive_original_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfoarchive',
            name='original_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
