# Generated by Django 5.2.3 on 2026-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_listedinfoarchive_original_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
    ]
