# Generated by Django 5.2.3 on 2026-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_alter_cardsearchresult_overall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='overall_trend',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='recent_trend',
            field=models.FloatField(default=0.0),
        ),
    ]
