# Generated by Django 5.2.3 on 2026-04-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_listinggroup_overall_trend_listinggroup_recent_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listinggroup',
            old_name='overall_trend',
            new_name='trend_overall',
        ),
        migrations.RenameField(
            model_name='listinggroup',
            old_name='recent_trend',
            new_name='trend_recent',
        ),
    ]
