# Generated by Django 5.2.3 on 2026-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_rename_overall_trend_listinggroup_trend_overall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='recent_date',
            field=models.DateField(null=True),
        ),
    ]
