# Generated by Django 5.2.3 on 2026-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_listinggroup_recent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='overall_start_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='recent_trand_start_price',
            field=models.FloatField(default=0.0),
        ),
    ]
