# Generated by Django 5.2.3 on 2026-04-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_listinggroup_overall_start_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listinggroup',
            old_name='recent_trand_start_price',
            new_name='recent_trend_start_price',
        ),
    ]
