# Generated by Django 5.2.3 on 2026-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_rename_recent_trand_start_price_listinggroup_recent_trend_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='overall_end_price',
            field=models.FloatField(default=0.0),
        ),
    ]
