# Generated by Django 5.2.3 on 2026-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_listinggroup_overall_end_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='trend_unfiltered',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='unfiltered_end_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='unfiltered_start_price',
            field=models.FloatField(default=0.0),
        ),
    ]
