# Generated by Django 5.2.3 on 2026-05-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_listinggroup_trend_unfiltered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='overall_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('sold', 'Sold'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_status', models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('sold', 'Sold'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='listed', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('sold_qty', models.IntegerField(default=0)),
                ('available_qty', models.IntegerField(default=0)),
                ('listing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listedinfo')),
            ],
        ),
    ]
