# Generated by Django 5.2.3 on 2026-05-02 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_alter_cardsearchresult_overall_status_listingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingstatus',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingstatus',
            name='listing_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_statuses', to='core.listedinfo'),
        ),
    ]
