# Generated by Django 5.2.3 on 2026-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_listingstatus_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingstatus',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='listingstatus',
            name='sold_value',
            field=models.FloatField(default=0),
        ),
    ]
