# Generated by Django 5.2.3 on 2026-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_alter_cardsearchresult_overall_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='max_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='max_offer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='min_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='min_offer',
            field=models.FloatField(default=0.0),
        ),
    ]
