# Generated by Django 5.2.3 on 2026-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_cardsearchresult_max_avg_cardsearchresult_max_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='last_5_max_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listinggroup',
            name='last_5_min_price',
            field=models.FloatField(default=0.0),
        ),
    ]
