# Generated by Django 5.2.3 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_listinggroup_last_5_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='scale_max',
            field=models.FloatField(default=0.0),
        ),
    ]
