# Generated by Django 5.2.3 on 2026-05-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_listinggroup_scale_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listinggroup',
            name='scale_max',
        ),
    ]
