# Generated by Django 5.2.3 on 2026-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_remove_listinggroup_scale_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinggroup',
            name='clusters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
