# Generated by Django 5.2.3 on 2026-05-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_listinggroup_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_filter_terms_is_manual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_filter_terms_m',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
