# Generated by Django 5.2.3 on 2026-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_cardsearchresult_parallel_filter_terms_is_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='parallel_filter_terms_m',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
