# Generated by Django 5.2.3 on 2026-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_alter_cardsearchresult_parallel_filter_terms_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='parallel_filter_terms',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
