# Generated by Django 5.2.3 on 2026-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_alter_cardsearchresult_parallel_filter_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinggroup',
            name='filter_terms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listinggroup',
            name='id_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='thumb_url',
            field=models.CharField(max_length=500),
        ),
    ]
