# Generated by Django 5.2.3 on 2026-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_alter_listinggroup_filter_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
