# Generated by Django 5.2.3 on 2026-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_alter_cardsearchresult_overall_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingstatus',
            name='create_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
