# Generated by Django 5.2.3 on 2026-05-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_listingstatus_create_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingstatus',
            name='create_sku',
        ),
    ]
