# Generated by Django 5.2.3 on 2026-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_listingstatus_create_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
