# Generated by Django 5.2.3 on 2026-06-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_alter_productlisting_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='master_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='core.card'),
        ),
    ]
