# Generated by Django 5.2.3 on 2026-06-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_card_master_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='replaced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.productgroup'),
        ),
        migrations.AlterField(
            model_name='listinggroup',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='img_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
