# Generated by Django 5.2.3 on 2026-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_card_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=50)),
                ('group_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='tag_groups',
            field=models.ManyToManyField(blank=True, related_name='tagged_cards', to='core.taggroup'),
        ),
    ]
