# Generated by Django 5.2.3 on 2026-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_taggroup_card_tag_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='exportedOffer',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
