# Generated by Django 5.2.3 on 2026-06-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_listedinfo_exportedoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='brand_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='card_name_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='card_number_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='city_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='full_name_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='parallel_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='serial_number_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='subset_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='team_available_tokens',
        ),
        migrations.RemoveField(
            model_name='cardsearchresult',
            name='year_available_tokens',
        ),
    ]
