# Generated by Django 5.2.3 on 2026-06-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_alter_cardsearchresult_card_name_selected_token'),
        ('services', '0062_bulklistingtask_alter_task_predecessor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='brand_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csr_as_selected_brand', to='services.brand'),
        ),
    ]
