# Generated by Django 5.2.3 on 2026-07-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_alter_cardsearchresult_brand_selected_token'),
        ('services', '0065_alter_playeryearteamcity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='subset_selected_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csr_as_selected_subset', to='services.subset'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='search_result',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.cardsearchresult'),
        ),
    ]
