# Generated by Django 5.2.3 on 2026-07-27 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_alter_productlisting_search_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='creation_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgroup',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
