# Generated by Django 5.2.3 on 2026-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_productgroup_creation_dt_productgroup_modified_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='avail_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='avail_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='listed_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='sold_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='total_listing_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='avail_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='avail_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='listed_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='listed_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='sold_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='sold_qty',
            field=models.IntegerField(default=0),
        ),
    ]
