# Generated by Django 5.2.3 on 2026-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_listedinfo_avail_price_listedinfo_avail_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='staged_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='staged_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
