# Generated by Django 5.2.3 on 2026-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_productgroup_staged_price_productgroup_staged_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='listed_sku',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
