# Generated by Django 5.2.3 on 2026-08-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_listedinfo_listed_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='ebay_product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.productgroup'),
        ),
    ]
