# Generated by Django 5.2.3 on 2026-08-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_alter_cardsearchresult_ebay_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsearchresult',
            name='ebay_product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='core.productgroup'),
        ),
    ]
