# Generated by Django 5.2.3 on 2026-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_alter_cardsearchresult_ebay_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='is_pg',
            field=models.BooleanField(default=False),
        ),
    ]
