# Generated by Django 5.2.3 on 2026-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_listedinfo_is_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
