# Generated by Django 5.2.3 on 2026-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_listedinfo_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedinfo',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
