# Generated by Django 5.2.3 on 2026-08-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_listedinfo_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='as_recent_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_listings_rel', to='core.listinggroup'),
        ),
    ]
