# Generated by Django 5.2.3 on 2026-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_productlisting_as_recent_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsearchresult',
            name='sell_through_rate_recent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cardsearchresult',
            name='sell_through_rate_total',
            field=models.FloatField(default=0.0),
        ),
    ]
