# Generated by Django 5.2.3 on 2026-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_cardsearchresult_sell_through_rate_recent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='listing_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
