# Generated by Django 5.2.3 on 2026-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_productgroup_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='listing_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='listing_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='skus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
