# Generated by Django 5.2.3 on 2026-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_productgroup_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='listing_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('sold', 'Sold'), ('confirmed', 'Confirmed'), ('unknown', 'Unknown'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='imported', max_length=20),
        ),
    ]
