# Generated by Django 5.2.3 on 2026-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_alter_productgroup_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='skus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
