# Generated by Django 5.2.3 on 2026-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_alter_productgroup_skus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='listing_str',
            field=models.FloatField(default=0.0),
        ),
    ]
