# Generated by Django 5.2.3 on 2026-08-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_productgroup_listing_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedinfo',
            name='sub_cards',
        ),
        migrations.AddField(
            model_name='listedinfo',
            name='assigned_product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_group_member', to='core.productgroup'),
        ),
    ]
