# Generated by Django 5.2.3 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_remove_listedinfo_sub_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='title_format',
            field=models.CharField(choices=[('player group', 'Player Group'), ('set group', 'Set Group'), ('team group', 'Team Group')], default='player group', max_length=20),
        ),
    ]
