# Generated by Django 5.2.3 on 2026-08-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_productgroup_title_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedinfo',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_products_info', to='core.productgroup'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='title_format',
            field=models.CharField(choices=[('player group', 'Player Group'), ('set group', 'Set Group'), ('team group', 'Team Group'), ('misc group', 'Misc Group')], default='misc group', max_length=20),
        ),
    ]
