# Generated by Django 5.2.3 on 2026-09-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_alter_listedinfo_product_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtitle',
            name='parent_listing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='core.productlisting'),
        ),
    ]
