# Generated by Django 5.2.3 on 2025-07-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='active_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('home_city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='services.city')),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='services.settings')),
            ],
        ),
        migrations.CreateModel(
            name='KnownName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribs', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='services.brand')),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key', 'parent_brand')},
            },
        ),
    ]
