# Generated by Django 5.2.3 on 2025-07-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('raw_value', 'parent_settings', 'field_key', 'home_city')},
        ),
    ]
