# Generated by Django 5.2.3 on 2025-07-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_cardnumber_season_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='nr_returned_listings',
            field=models.IntegerField(default=10),
        ),
    ]
