# Generated by Django 5.2.3 on 2025-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_settings_nr_returned_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='export_file_location',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
