# Generated by Django 5.2.3 on 2025-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_settings_export_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='nr_collection_page_items',
            field=models.IntegerField(default=10),
        ),
    ]
