# Generated by Django 5.2.3 on 2025-08-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_settings_nr_collection_page_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='export_file_location',
        ),
    ]
