# Generated by Django 5.2.3 on 2025-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_settings_export_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownname',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knownname',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knownname',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
