# Generated by Django 5.2.3 on 2025-08-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_knownname_is_first_knownname_is_full_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(default='None', max_length=100)),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
    ]
