# Generated by Django 5.2.3 on 2025-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardnumber',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knownname',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subset',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='match_source_formatting',
            field=models.BooleanField(default=False),
        ),
    ]
