# Generated by Django 5.2.3 on 2025-08-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_brand_match_source_formatting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='field_key',
            field=models.CharField(default='brands', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='field_key',
            field=models.CharField(default='attribs', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardnumber',
            name='field_key',
            field=models.CharField(default='cardnr', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='field_key',
            field=models.CharField(default='cities', max_length=100),
        ),
        migrations.AlterField(
            model_name='condition',
            name='field_key',
            field=models.CharField(default='condition', max_length=100),
        ),
        migrations.AlterField(
            model_name='knownname',
            name='field_key',
            field=models.CharField(default='names', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='field_key',
            field=models.CharField(default='season', max_length=100),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='field_key',
            field=models.CharField(default='serial', max_length=100),
        ),
        migrations.AlterField(
            model_name='subset',
            name='field_key',
            field=models.CharField(default='subsets', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='field_key',
            field=models.CharField(default='teams', max_length=100),
        ),
    ]
