# Generated by Django 5.2.3 on 2025-08-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_brand_field_key_alter_cardattribute_field_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('match_source_formatting', models.BooleanField(default=False)),
                ('field_key', models.CharField(default='parallel', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parallel', to='services.settings')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
    ]
