# Generated by Django 5.2.3 on 2025-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardattribute',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
