# Generated by Django 5.2.3 on 2025-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_cardattribute_primary_attrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='field_pct_threshold',
            field=models.FloatField(default=0.3),
        ),
    ]
