# Generated by Django 5.2.3 on 2025-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_settings_field_pct_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cardnumber',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='condition',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='knownname',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parallel',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='season',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subset',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
