# Generated by Django 5.2.3 on 2025-08-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_brand_primary_attrib_cardnumber_primary_attrib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.brand'),
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.cardattribute'),
        ),
        migrations.AddField(
            model_name='cardnumber',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.cardnumber'),
        ),
        migrations.AddField(
            model_name='city',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.city'),
        ),
        migrations.AddField(
            model_name='condition',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.condition'),
        ),
        migrations.AddField(
            model_name='knownname',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.knownname'),
        ),
        migrations.AddField(
            model_name='parallel',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.parallel'),
        ),
        migrations.AddField(
            model_name='season',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.season'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.serialnumber'),
        ),
        migrations.AddField(
            model_name='subset',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.subset'),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.team'),
        ),
    ]
