# Generated by Django 5.2.3 on 2025-08-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_brand_primary_token_cardattribute_primary_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='parent_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='year', to='services.settings'),
        ),
    ]
