# Generated by Django 5.2.3 on 2025-08-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_brand_disabled_date_cardattribute_disabled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(default='', max_length=100)),
                ('match_source_formatting', models.BooleanField(default=False)),
                ('primary_attrib', models.CharField(blank=True, default='', max_length=100)),
                ('disabled_date', models.DateTimeField(blank=True, null=True)),
                ('field_key', models.CharField(default='card_name', max_length=100)),
                ('parent_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_name', to='services.settings')),
                ('primary_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_tokens', to='services.cardname')),
            ],
            options={
                'unique_together': {('raw_value', 'parent_settings', 'field_key')},
            },
        ),
    ]
