# Generated by Django 5.2.3 on 2025-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_cardname'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ebay_user_auth_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
