# Generated by Django 5.2.3 on 2025-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_settings_ebay_user_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ebay_access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='ebay_access_token_expiration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='ebay_refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='ebay_refresh_token_expiration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='ebay_user_auth_code_expiration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
