# Generated by Django 5.2.3 on 2025-08-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_settings_ebay_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ebay_access_token_expiration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ebay_refresh_token_expiration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ebay_user_auth_code_expiration',
            field=models.FloatField(default=0.0),
        ),
    ]
