# Generated by Django 5.2.3 on 2025-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_settings_ebay_access_token_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ebay_user_auth_consent',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
