# Generated by Django 5.2.3 on 2025-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_settings_ebay_user_auth_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ebay_access_token',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ebay_refresh_token',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ebay_user_auth_code',
            field=models.CharField(blank=True),
        ),
    ]
