# Generated by Django 5.2.3 on 2025-08-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_settings_ebay_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ebay_user_auth_consent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
