# Generated by Django 5.2.3 on 2025-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_settings_ebay_user_auth_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ebay_auth_code_unescaped',
            field=models.CharField(blank=True),
        ),
    ]
