# Generated by Django 5.2.3 on 2025-08-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_settings_ebay_auth_code_unescaped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='ebay_user_auth_code_expiration',
        ),
    ]
