# Generated by Django 5.2.3 on 2025-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_settings_ebay_user_auth_code_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='ebay_id_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='condition',
            name='ebay_string_value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
