# Generated by Django 5.2.3 on 2025-09-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_condition_ebay_id_value_condition_ebay_string_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='nr_std_devs',
            field=models.FloatField(default=2.0),
        ),
    ]
