# Generated by Django 5.2.3 on 2025-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_settings_nr_std_devs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='nr_returned_listings',
            new_name='id_listings',
        ),
        migrations.AddField(
            model_name='settings',
            name='price_listings',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='refined_listings',
            field=models.IntegerField(default=10),
        ),
    ]
