# Generated by Django 5.2.3 on 2025-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_rename_nr_returned_listings_settings_id_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='run_pricing_after_refine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='run_refine_after_id',
            field=models.BooleanField(default=False),
        ),
    ]
