# Generated by Django 5.2.3 on 2026-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
