# Generated by Django 5.2.3 on 2026-01-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_collection_status'),
        ('services', '0033_task_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.AddField(
            model_name='task',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='core.card'),
        ),
    ]
