# Generated by Django 5.2.3 on 2026-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_remove_task_img_task_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_str',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('listed', 'Listed'), ('pending', 'Pending'), ('failed', 'Failed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
