# Generated by Django 5.2.3 on 2026-02-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_cardsearchresult_back_cropping_status_and_more'),
        ('services', '0035_task_error_str_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='card',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='core.card')),
                ('csr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='core.cardsearchresult')),
            ],
            bases=('services.task',),
        ),
    ]
