# Generated by Django 5.2.3 on 2026-02-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_cardsearchresult_back_cropping_status_and_more'),
        ('services', '0036_remove_task_card_alter_task_status_listingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtask',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_tasks', to='core.card'),
        ),
        migrations.AlterField(
            model_name='listingtask',
            name='csr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_tasks', to='core.cardsearchresult'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unexecuted', 'Unexecuted'), ('listed', 'Listed'), ('pending', 'Pending'), ('manual', 'Manual'), ('auto', 'Auto'), ('locked', 'Locked'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PricingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing_tasks', to='core.card')),
                ('csr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_pricing_tasks', to='core.cardsearchresult')),
            ],
            bases=('services.task',),
        ),
    ]
