# Generated by Django 5.2.3 on 2026-02-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_card_listing_details'),
        ('services', '0038_alter_listingtask_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtask',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tasks', to='core.card'),
        ),
    ]
