# Generated by Django 5.2.3 on 2026-03-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_pricingtask_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='field_key',
            field=models.CharField(default='brands', max_length=500),
        ),
        migrations.AlterField(
            model_name='brand',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='brand',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='field_key',
            field=models.CharField(default='attribs', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='field_key',
            field=models.CharField(default='card_name', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardname',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardnumber',
            name='field_key',
            field=models.CharField(default='cardnr', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardnumber',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cardnumber',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='city',
            name='field_key',
            field=models.CharField(default='cities', max_length=500),
        ),
        migrations.AlterField(
            model_name='city',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='city',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='condition',
            name='field_key',
            field=models.CharField(default='condition', max_length=500),
        ),
        migrations.AlterField(
            model_name='condition',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='condition',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='knownname',
            name='field_key',
            field=models.CharField(default='names', max_length=500),
        ),
        migrations.AlterField(
            model_name='knownname',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='knownname',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parallel',
            name='field_key',
            field=models.CharField(default='parallel', max_length=500),
        ),
        migrations.AlterField(
            model_name='parallel',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='parallel',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='season',
            name='field_key',
            field=models.CharField(default='season', max_length=500),
        ),
        migrations.AlterField(
            model_name='season',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='season',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='field_key',
            field=models.CharField(default='serial', max_length=500),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subset',
            name='field_key',
            field=models.CharField(default='subsets', max_length=500),
        ),
        migrations.AlterField(
            model_name='subset',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subset',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='field_key',
            field=models.CharField(default='teams', max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='primary_attrib',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='raw_value',
            field=models.CharField(default='', max_length=500),
        ),
    ]
