# Generated by Django 5.2.3 on 2026-03-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_alter_brand_field_key_alter_brand_primary_attrib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
            ],
            bases=('services.task',),
        ),
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
            ],
            bases=('services.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='services.task'),
        ),
    ]
