# Generated by Django 5.2.3 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_idtask_uploadtask_task_predecessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('priced', 'Priced'), ('listed', 'Listed'), ('running', 'Running'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
