# Generated by Django 5.2.3 on 2026-03-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_remove_cardsearchresult_back_cropping_status_and_more'),
        ('services', '0042_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtask',
            name='csr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricing_tasks', to='core.cardsearchresult'),
        ),
    ]
