# Generated by Django 5.2.3 on 2026-03-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_alter_pricingtask_csr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='successor', to='services.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('priced', 'Priced'), ('listed', 'Listed'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
