# Generated by Django 5.2.3 on 2026-03-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_cardsearchresult_overall_status'),
        ('services', '0044_alter_task_predecessor_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtask',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tasks', to='core.card'),
        ),
    ]
