# Generated by Django 5.2.3 on 2026-04-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_alter_task_on_success_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subset',
            unique_together={('raw_value', 'parent_settings', 'field_key')},
        ),
        migrations.AlterField(
            model_name='subset',
            name='parent_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='services.brand'),
        ),
    ]
