# Generated by Django 5.2.3 on 2026-04-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_alter_subset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subset',
            unique_together=set(),
        ),
    ]
