# Generated by Django 5.2.3 on 2026-05-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_task_completed_at_task_executed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parallel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parallel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='services.brand'),
        ),
        migrations.AddField(
            model_name='parallel',
            name='search_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parallel',
            name='subset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='services.subset'),
        ),
        migrations.AlterUniqueTogether(
            name='parallel',
            unique_together={('raw_value', 'parent_settings', 'field_key', 'brand', 'subset')},
        ),
    ]
