# Generated by Django 5.2.3 on 2026-05-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_alter_parallel_unique_together_parallel_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='services.brand'),
        ),
        migrations.AlterField(
            model_name='parallel',
            name='subset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='services.subset'),
        ),
    ]
