# Generated by Django 5.2.3 on 2026-05-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_alter_parallel_brand_alter_parallel_subset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parallel',
            old_name='search_string',
            new_name='filter_terms',
        ),
        migrations.AlterUniqueTogether(
            name='parallel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parallel',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='services.season'),
        ),
        migrations.AlterUniqueTogether(
            name='parallel',
            unique_together={('raw_value', 'parent_settings', 'field_key', 'year', 'brand', 'subset')},
        ),
    ]
