# Generated by Django 5.2.3 on 2026-05-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_productlisting_bids'),
        ('services', '0058_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_tasks', to='core.card')),
            ],
            bases=('services.task',),
        ),
    ]
