# Generated by Django 5.2.3 on 2026-05-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_confirmtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownname',
            name='primary_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='names', to='services.city'),
        ),
        migrations.AddField(
            model_name='knownname',
            name='primary_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='names', to='services.team'),
        ),
    ]
