# Generated by Django 5.2.3 on 2026-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_knownname_primary_city_knownname_primary_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_run_usered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='on_success_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('sold', 'Sold'), ('confirmed', 'Confirmed'), ('unknown', 'Unknown'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('identified', 'Identified'), ('auto-priced', 'Auto-Priced'), ('priced', 'Priced'), ('listed', 'Listed'), ('held', 'Held'), ('archived', 'Archived'), ('unlisted', 'Unlisted'), ('rehydrated', 'Rehydrated'), ('reviewed', 'Reviewed'), ('sold', 'Sold'), ('confirmed', 'Confirmed'), ('unknown', 'Unknown'), ('running', 'Running'), ('staged', 'Staged'), ('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
