# Generated by Django 5.2.3 on 2026-06-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_settings_last_run_usered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkListingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.task')),
            ],
            bases=('services.task',),
        ),
        migrations.AlterField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='successors', to='services.task'),
        ),
        migrations.AddField(
            model_name='listingtask',
            name='bulk_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_tasks', to='services.bulklistingtask'),
        ),
    ]
