# Generated by Django 5.2.3 on 2026-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_bulklistingtask_alter_task_predecessor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='listingtask',
            name='bulk_task',
        ),
        migrations.AddField(
            model_name='bulklistingtask',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
