# Generated by Django 5.2.3 on 2026-07-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0063_rename_name_task_title_remove_listingtask_bulk_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knownname',
            name='primary_city',
        ),
        migrations.RemoveField(
            model_name='knownname',
            name='primary_team',
        ),
        migrations.CreateModel(
            name='PlayerYearTeamCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.city')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.knownname')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.team')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.season')),
            ],
            options={
                'unique_together': {('player_name', 'year', 'team', 'city')},
            },
        ),
    ]
