# Generated by Django 5.2.3 on 2026-07-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_remove_knownname_primary_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeryearteamcity',
            unique_together={('player_name', 'year')},
        ),
        migrations.AlterField(
            model_name='playeryearteamcity',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.city'),
        ),
        migrations.AlterField(
            model_name='playeryearteamcity',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyt_mappings', to='services.team'),
        ),
    ]
